# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flutter-demo' do
  use_frameworks!
#  pod 'Flutter', :podspec => '../flutter-demo/flutterLib/Release/Flutter.podspec'
#  pod 'Flutter', :podspec => '../flutter-demo/flutterLib/Release/Flutter.podspec'
end
